x-default:
  &default-odoo
  tty: true
  volumes:
    - odoo-web-data:/var/lib/odoo
    - ./config:/etc/odoo
    - ./ou12:/opt/ou12
    - ./ou13:/opt/ou13
    - ./ou14:/opt/ou14
    - ./ou15:/opt/ou15
    - ./ou16:/opt/ou16
    - ./ou17:/opt/ou17
    - ./ou18:/opt/ou18
    - ./vendor:/opt/vendor
  ports:
    - 127.0.0.1:9999:8069

x-defaultdev:
  &default-odoodev
  tty: true
  volumes:
    - odoo-web-data:/var/lib/odoo
    - ./config:/etc/odoo
    - ../../common:/mnt/common:ro
    - ./:/mnt/project:ro
  ports:
    - 127.0.0.1:9999:8069
  environment:
    - WDB_SOCKET_SERVER=wdb
    - WDB_NO_BROWSER_AUTO_OPEN=True

services:
  odoo12:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./12.0_Dockerfile_noou
    depends_on:
      - db
    command: [
    '-d', 'db',
    ]

  odoo13:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./13.0_Dockerfile
    depends_on:
      - db
    command: [
    '-d', 'db',
    ]

  odoo14:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./14.0_Dockerfile
    depends_on:
      - db
    command: [
    '-d', 'db',
    ]

  odoo15:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./15.0_Dockerfile
    depends_on:
      - db
    command: [
    '-d', 'db',
    ]

  odoo16:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./16.0_Dockerfile
    depends_on:
      - db
    command: [
    '-d', 'db',
    ]

  odoo17:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./17.0_Dockerfile
    depends_on:
      - db
    command: [
    '-d', 'db',
    ]

  odoo18:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./18.0_Dockerfile
    depends_on:
      - db
    command: [
    '-d', 'db',
    ]

  dev:
    << : *default-odoodev
    image: my/odoo:18.0
    depends_on:
      - db
      - wdb
    command: [
    '-d', 'db',
    '--addons-path', '/mnt/project/vendor/17.0/custom/,/mnt/common/odoo/odoo/addons',
    ]

  wdb:
    image: kozea/wdb:3.3.0
    ports:
      - "1984:1984"

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data-pers:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    command: ['postgres',
    '-c', 'fsync=off',
    '-c', 'synchronous_commit=off',
    '-c', 'full_page_writes=off',
    ]

volumes:
  odoo-web-data:
    driver_opts:
      type: tmpfs
      device: tmpfs
  odoo-db-data:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=13.5G"
  odoo-db-data-pers:
