version: '3.4'

x-default:
  &default-odoo
  tty: true
  volumes:
    - odoo-web-data:/var/lib/odoo
    - ./config:/etc/odoo
    - ./ou11:/opt/ou11
    - ./ou12:/opt/ou12
    - ./ou13:/opt/ou13
    - ./ou14:/opt/ou14
    - ./ou15:/opt/ou15
    - ./ou16:/opt/ou16
    - ./ou17:/opt/ou17
    - ./vendor:/opt/vendor
  ports:
    - 127.0.0.1:9999:8069

services:
  odoo11:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./11.0_Dockerfile
    depends_on:
      - db
    command: [
    '-d', 'turboc',
    ]

  odoo12:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./12.0_Dockerfile
    depends_on:
      - db
    command: [
    '-d', 'turboc',
    ]

  odoo13:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./13.0_Dockerfile
    depends_on:
      - db
    command: [
    '-d', 'turboc',
    ]

  odoo14:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./14.0_Dockerfile
    depends_on:
      - db
    command: [
    '-d', 'turboc',
    ]

  odoo15:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./15.0_Dockerfile
    depends_on:
      - db
    command: [
    '-d', 'turboc',
    ]

  odoo16:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./16.0_Dockerfile
    depends_on:
      - db
    command: [
    '-d', 'turboc',
    ]

  odoo17:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./17.0_Dockerfile
    depends_on:
      - db
    command: [
    '-d', 'turboc',
    ]

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    command: ['postgres',
    '-c', 'fsync=off',
    '-c', 'synchronous_commit=off',
    '-c', 'full_page_writes=off',
    ]

volumes:
  odoo-web-data:
  odoo-db-data:
