version: '3.4'

x-default:
  &default-odoo
  tty: true
  volumes:
    - odoo-web-data:/var/lib/odoo
    - ./config:/etc/odoo
    - ./ou13:/opt/ou13
    - ./ou14:/opt/ou14
    - ./vendor:/opt/vendor
  ports:
    - 8069:8069

services:
  odoo13:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./13.0_Dockerfile
    depends_on:
      - db

  odoo14:
    << : *default-odoo
    build:
      context: ./context
      dockerfile: ./14.0_Dockerfile
    depends_on:
      - db
    command: [
    '-d', 'korvetlog',
    ]

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

volumes:
  odoo-web-data:
  odoo-db-data:
